FROM wisrovi/agents:gpu-slim-dvc

SHELL ["bash", "-c"]

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY src/ /app/src/
COPY api.py /app/api.py
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

EXPOSE 7860

CMD [ "python", "/app/api.py" ]
