services:

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: wisrovi/dataset-ia:worker-v1
    volumes:
      - /mnt/dataset-ia/projects:/app/projects
      # - ./dvc/config:/app/.dvc/config
      # - ./worker.py:/app/worker.py
      # - ./src:/app/src
      # - ./dvc.lock:/app/dvc.lock
      # - ./dvc.yaml:/app/dvc.yaml
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4g
    # stdin_open: true
    # tty: true
    hostname: wDVC
    restart: always
    # command: tail -f /dev/null
    # init: true
    environment:
      - IP_HOST=192.168.1.84
      - REDIS_HOST=192.168.10.108
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
