FROM wisrovi/agents:gpu-slim-dvc
SHELL ["bash", "-c"]

WORKDIR /app



RUN git config --global --add safe.directory /app && \
    git config --system --add safe.directory /app

COPY .dvc/ /app/.dvc/
COPY dvc.lock /app/dvc.lock
COPY dvc.yaml /app/dvc.yaml

# git config
RUN git init
RUN git remote add origin https://github.com/wisrovi/dataset-IA.git
RUN git config --global user.email "wrodriguez@ecapturedtech.com"
RUN git config --global user.name "wrodriguez"
RUN git checkout -b DEVELOPMENT
RUN git add .
RUN git commit -m "Eliminar archivos DVC conflictivos"


# create example_output.txt
RUN echo "example_output.txt" > example_output.txt

RUN apt update && apt install nload -y

# dvc remove
RUN dvc remove example
RUN dvc gc --workspace -f

COPY src/scripts/api/requirements.txt /app/requirements.txt
RUN python -m pip install --no-cache-dir -r /app/requirements.txt

HEALTHCHECK --interval=5m --timeout=30s --start-period=2m --retries=3 \
    CMD CURRENT_SIZE=$(du -sb / --exclude=/app/projects --exclude=/proc --exclude=/sys --exclude=/dev | cut -f1); \
    LIMIT=$((50 * 1024 * 1024 * 1024)); \
    if [ "$CURRENT_SIZE" -gt "$LIMIT" ]; then exit 1; else exit 0; fi


COPY worker.py /app/worker.py
COPY src/ /app/src/

CMD ["python", "/app/worker.py"]
