services:
  redis:
    image: redislabs/redismod
    ports:
      - "6379:6379"
    command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "4468:8081"
    depends_on:
      - redis

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: wisrovi/dataset-ia:api-v1
    ports:
      - "4467:7860"
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    restart: unless-stopped
    # command: tail -f /dev/null
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
