services:
  worker:
    image: wisrovi/dataset-ia:worker-v1
    volumes:
      - /mnt/dataset-ia/projects:/app/projects
    shm_size: 16g
    hostname: wDVC
    restart: always
    environment:
      - IP_HOST=192.168.1.84
      - REDIS_HOST=192.168.10.108
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4g
    # init: true
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_SCHEDULE=0 0 0,2,4,6,8,10,12,14,16,18,20,22 * * *
      - WATCHTOWER_CLEANUP=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
